### ISSUE TITLE
請問Webview裡的網頁有沒有辦法達到縮放

### ISSUE THREAD

**Issue by scozirge** [arclee/ArcAndroidToolPlugin#1]
您好，我也是遊戲開發者，想要請教一些WebView的問題，不知道有沒有什麼方法可以連絡你(FB、SKYPE、Line等)，我本身有使用Unity但是對AndroidPlugin不太熟，不知道有沒有方法可以做到縮放Webview的網頁，就像用瀏覽器開啟那樣? 謝謝

**Comment by arclee** [comment]
縮放？

你是說這個嗎？

http://fecbob.pixnet.net/blog/post/35579531-android-webview%E6%94%BE%E5%A4%A7%E7%B8%AE%E5%B0%8F%E7%B8%AE%E6%94%BE

scozirge notifications@github.com 於 2015年8月6日 下午3:16 寫道：

**Comment by scozirge** [comment]
看起來應該是，不過我只用Unity寫C#，還沒有使用Android寫Plugin給Unity使用過，我再研究看看，感謝你的回覆!

arclee notifications@github.com 於 2015年8月6日 下午8:20 寫道：

**Comment by scozirge** [comment]
您好，我用eclipse寫了webView後，有些問題想請教。
1.發現我的weeView會有一個框架包住網頁，標題寫MyWebview，但你的只顯示網頁沒有框框，請問是怎麼辦到的
2.另外是，我該怎麼像你寫的範例一樣能在untiy裡用c#控制webView的大小或位置
不好意思，問題有點多，因為之前沒用過android程式:(
感謝您

**Comment by scozirge** [comment]
不好意思 另外再補充問一點，我在unity輸出成apk檔案時，Bundle Identifier必須是 com.example.webview​
跟我android project的檔名一樣，但你範例中Bundle Identifier 我不需要與您的plugin專案名稱一樣，這是怎麼做的?

**Comment by arclee** [comment]
你可以試著把我的 jar 反組譯來看看哦～沒關係的哦～我沒有加密與混淆。

2015-08-10 10:59 GMT+08:00 scozirge notifications@github.com:
